name: Run Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Export Firefox binary path for tests
        run: echo "FIREFOX_BIN=/opt/hostedtoolcache/firefox/latest/x64/firefox" >> $GITHUB_ENV

      - name: Set up Geckodriver
        uses: browser-actions/setup-geckodriver@latest

      - name: Run tests
        run: mvn test